/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:188c756c-c3b2-415b-9871-240672b024bb",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_GsGRFn1hk",
    "aws_user_pools_web_client_id": "6uq49314el2rqi6m3nmb9ksicb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://shttckr2bjci7hecjpwgsdwhhu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
